version: '3'

services:

    api:
        container_name: app #Name can be anything
        restart: always
        build: ./app
        ports:
            - "8000:8000"
        command: gunicorn -w 1 -b :8000 chatgphitAPP:APP
        
    nginx:
        container_name: nginx
        restart: always
        build: ./nginx
        ports:
            - "8001:8001"
        depends_on:
            - api